# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://wings-club.github.io/
title: Wings Club
email: contato@cesar.school
author: Time Wings Club
description: > # "Write an awesome description for your new site here. 
  Blog do grupo D do Cesar School com o cliente Wings 
copyright: 'Copyright &copy; 2018 Time Wings Club. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/Wings-Club
